//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.11 at 09:49:38 PM EET 
//


package com.pos.transprocessor.input.json;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for itemizationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="itemizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="total_money" type="{}total_moneyType"/>
 *         &lt;element name="single_quantity_money" type="{}single_quantity_moneyType"/>
 *         &lt;element name="gross_sales_money" type="{}gross_sales_moneyType"/>
 *         &lt;element name="discount_money" type="{}discount_moneyType"/>
 *         &lt;element name="net_sales_money" type="{}net_sales_moneyType"/>
 *         &lt;element name="category" type="{}categoryType"/>
 *         &lt;element name="variation" type="{}variationType"/>
 *         &lt;element name="taxes" type="{}taxesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modifiers" type="{}modifiersType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemizationType", propOrder = {
        "id",
        "name",
        "quantity",
        "totalMoney",
        "singleQuantityMoney",
        "grossSalesMoney",
        "discountMoney",
        "netSalesMoney",
        "category",
        "variation",
        "taxes",
        "modifiers"
})
public class ItemizationType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String name;
    protected byte quantity;
    @XmlElement(name = "total_money", required = true)
    protected TotalMoneyType totalMoney;
    @XmlElement(name = "single_quantity_money", required = true)
    protected SingleQuantityMoneyType singleQuantityMoney;
    @XmlElement(name = "gross_sales_money", required = true)
    protected GrossSalesMoneyType grossSalesMoney;
    @XmlElement(name = "discount_money", required = true)
    protected DiscountMoneyType discountMoney;
    @XmlElement(name = "net_sales_money", required = true)
    protected NetSalesMoneyType netSalesMoney;
    @XmlElement(required = true)
    protected CategoryType category;
    @XmlElement(required = true)
    protected VariationType variation;
    protected List<TaxesType> taxes;
    @XmlElement(required = true)
    protected ModifiersType modifiers;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the quantity property.
     */
    public byte getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     */
    public void setQuantity(byte value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the totalMoney property.
     *
     * @return possible object is
     * {@link TotalMoneyType }
     */
    public TotalMoneyType getTotalMoney() {
        return totalMoney;
    }

    /**
     * Sets the value of the totalMoney property.
     *
     * @param value allowed object is
     *              {@link TotalMoneyType }
     */
    public void setTotalMoney(TotalMoneyType value) {
        this.totalMoney = value;
    }

    /**
     * Gets the value of the singleQuantityMoney property.
     *
     * @return possible object is
     * {@link SingleQuantityMoneyType }
     */
    public SingleQuantityMoneyType getSingleQuantityMoney() {
        return singleQuantityMoney;
    }

    /**
     * Sets the value of the singleQuantityMoney property.
     *
     * @param value allowed object is
     *              {@link SingleQuantityMoneyType }
     */
    public void setSingleQuantityMoney(SingleQuantityMoneyType value) {
        this.singleQuantityMoney = value;
    }

    /**
     * Gets the value of the grossSalesMoney property.
     *
     * @return possible object is
     * {@link GrossSalesMoneyType }
     */
    public GrossSalesMoneyType getGrossSalesMoney() {
        return grossSalesMoney;
    }

    /**
     * Sets the value of the grossSalesMoney property.
     *
     * @param value allowed object is
     *              {@link GrossSalesMoneyType }
     */
    public void setGrossSalesMoney(GrossSalesMoneyType value) {
        this.grossSalesMoney = value;
    }

    /**
     * Gets the value of the discountMoney property.
     *
     * @return possible object is
     * {@link DiscountMoneyType }
     */
    public DiscountMoneyType getDiscountMoney() {
        return discountMoney;
    }

    /**
     * Sets the value of the discountMoney property.
     *
     * @param value allowed object is
     *              {@link DiscountMoneyType }
     */
    public void setDiscountMoney(DiscountMoneyType value) {
        this.discountMoney = value;
    }

    /**
     * Gets the value of the netSalesMoney property.
     *
     * @return possible object is
     * {@link NetSalesMoneyType }
     */
    public NetSalesMoneyType getNetSalesMoney() {
        return netSalesMoney;
    }

    /**
     * Sets the value of the netSalesMoney property.
     *
     * @param value allowed object is
     *              {@link NetSalesMoneyType }
     */
    public void setNetSalesMoney(NetSalesMoneyType value) {
        this.netSalesMoney = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return possible object is
     * {@link CategoryType }
     */
    public CategoryType getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is
     *              {@link CategoryType }
     */
    public void setCategory(CategoryType value) {
        this.category = value;
    }

    /**
     * Gets the value of the variation property.
     *
     * @return possible object is
     * {@link VariationType }
     */
    public VariationType getVariation() {
        return variation;
    }

    /**
     * Sets the value of the variation property.
     *
     * @param value allowed object is
     *              {@link VariationType }
     */
    public void setVariation(VariationType value) {
        this.variation = value;
    }

    /**
     * Gets the value of the taxes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxesType }
     */
    public List<TaxesType> getTaxes() {
        if (taxes == null) {
            taxes = new ArrayList<TaxesType>();
        }
        return this.taxes;
    }

    /**
     * Gets the value of the modifiers property.
     *
     * @return possible object is
     * {@link ModifiersType }
     */
    public ModifiersType getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     *
     * @param value allowed object is
     *              {@link ModifiersType }
     */
    public void setModifiers(ModifiersType value) {
        this.modifiers = value;
    }

}
