//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.11 at 09:49:38 PM EET 
//


package com.pos.transprocessor.input.json;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.pos.com.pos.transProcessor.json package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Root_QNAME = new QName("", "root");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pos.com.pos.transProcessor.json
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RootType }
     */
    public RootType createRootType() {
        return new RootType();
    }

    /**
     * Create an instance of {@link TotalMoneyType }
     */
    public TotalMoneyType createTotalMoneyType() {
        return new TotalMoneyType();
    }

    /**
     * Create an instance of {@link CreatorType }
     */
    public CreatorType createCreatorType() {
        return new CreatorType();
    }

    /**
     * Create an instance of {@link TaxesType }
     */
    public TaxesType createTaxesType() {
        return new TaxesType();
    }

    /**
     * Create an instance of {@link TaxMoneyType }
     */
    public TaxMoneyType createTaxMoneyType() {
        return new TaxMoneyType();
    }

    /**
     * Create an instance of {@link PriceMoneyType }
     */
    public PriceMoneyType createPriceMoneyType() {
        return new PriceMoneyType();
    }

    /**
     * Create an instance of {@link ModifiersType }
     */
    public ModifiersType createModifiersType() {
        return new ModifiersType();
    }

    /**
     * Create an instance of {@link TotalCollectedMoneyType }
     */
    public TotalCollectedMoneyType createTotalCollectedMoneyType() {
        return new TotalCollectedMoneyType();
    }

    /**
     * Create an instance of {@link SingleQuantityMoneyType }
     */
    public SingleQuantityMoneyType createSingleQuantityMoneyType() {
        return new SingleQuantityMoneyType();
    }

    /**
     * Create an instance of {@link GrossSalesMoneyType }
     */
    public GrossSalesMoneyType createGrossSalesMoneyType() {
        return new GrossSalesMoneyType();
    }

    /**
     * Create an instance of {@link ItemizationType }
     */
    public ItemizationType createItemizationType() {
        return new ItemizationType();
    }

    /**
     * Create an instance of {@link CategoryType }
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link TenderType }
     */
    public TenderType createTenderType() {
        return new TenderType();
    }

    /**
     * Create an instance of {@link RefundedMoneyType }
     */
    public RefundedMoneyType createRefundedMoneyType() {
        return new RefundedMoneyType();
    }

    /**
     * Create an instance of {@link NetSalesMoneyType }
     */
    public NetSalesMoneyType createNetSalesMoneyType() {
        return new NetSalesMoneyType();
    }

    /**
     * Create an instance of {@link DiscountMoneyType }
     */
    public DiscountMoneyType createDiscountMoneyType() {
        return new DiscountMoneyType();
    }

    /**
     * Create an instance of {@link InclusiveTaxMoneyType }
     */
    public InclusiveTaxMoneyType createInclusiveTaxMoneyType() {
        return new InclusiveTaxMoneyType();
    }

    /**
     * Create an instance of {@link AdditiveTaxMoneyType }
     */
    public AdditiveTaxMoneyType createAdditiveTaxMoneyType() {
        return new AdditiveTaxMoneyType();
    }

    /**
     * Create an instance of {@link VariationType }
     */
    public VariationType createVariationType() {
        return new VariationType();
    }

    /**
     * Create an instance of {@link TipMoneyType }
     */
    public TipMoneyType createTipMoneyType() {
        return new TipMoneyType();
    }

    /**
     * Create an instance of {@link AppliedMoneyType }
     */
    public AppliedMoneyType createAppliedMoneyType() {
        return new AppliedMoneyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootType }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "root")
    public JAXBElement<RootType> createRoot(RootType value) {
        return new JAXBElement<RootType>(_Root_QNAME, RootType.class, null, value);
    }

}
