//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.11 at 09:49:38 PM EET 
//


package com.pos.transprocessor.input.json;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for rootType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rootType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="business_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="location_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transaction_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="receipt_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serial_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dining_option" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creation_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="discount_money" type="{}discount_moneyType"/>
 *         &lt;element name="additive_tax_money" type="{}additive_tax_moneyType"/>
 *         &lt;element name="inclusive_tax_money" type="{}inclusive_tax_moneyType"/>
 *         &lt;element name="refunded_money" type="{}refunded_moneyType"/>
 *         &lt;element name="tax_money" type="{}tax_moneyType"/>
 *         &lt;element name="tip_money" type="{}tip_moneyType"/>
 *         &lt;element name="total_collected_money" type="{}total_collected_moneyType"/>
 *         &lt;element name="creator" type="{}creatorType"/>
 *         &lt;element name="tender" type="{}tenderType"/>
 *         &lt;element name="taxes" type="{}taxesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="itemization" type="{}itemizationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rootType", propOrder = {
        "id",
        "businessId",
        "locationId",
        "transactionId",
        "receiptId",
        "serialNumber",
        "diningOption",
        "creationTime",
        "discountMoney",
        "additiveTaxMoney",
        "inclusiveTaxMoney",
        "refundedMoney",
        "taxMoney",
        "tipMoney",
        "totalCollectedMoney",
        "creator",
        "tender",
        "taxes",
        "itemization"
})
public class RootType {

    @XmlElement(name = "_id", required = true)
    protected String id;
    @XmlElement(name = "business_id", required = true)
    protected String businessId;
    @XmlElement(name = "location_id", required = true)
    protected String locationId;
    @XmlElement(name = "transaction_id", required = true)
    protected String transactionId;
    @XmlElement(name = "receipt_id", required = true)
    protected String receiptId;
    @XmlElement(name = "serial_number", required = true)
    protected String serialNumber;
    @XmlElement(name = "dining_option", required = true)
    protected String diningOption;
    @XmlElement(name = "creation_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlElement(name = "discount_money", required = true)
    protected DiscountMoneyType discountMoney;
    @XmlElement(name = "additive_tax_money", required = true)
    protected AdditiveTaxMoneyType additiveTaxMoney;
    @XmlElement(name = "inclusive_tax_money", required = true)
    protected InclusiveTaxMoneyType inclusiveTaxMoney;
    @XmlElement(name = "refunded_money", required = true)
    protected RefundedMoneyType refundedMoney;
    @XmlElement(name = "tax_money", required = true)
    protected TaxMoneyType taxMoney;
    @XmlElement(name = "tip_money", required = true)
    protected TipMoneyType tipMoney;
    @XmlElement(name = "total_collected_money", required = true)
    protected TotalCollectedMoneyType totalCollectedMoney;
    @XmlElement(required = true)
    protected CreatorType creator;
    @XmlElement(required = true)
    protected TenderType tender;
    protected List<TaxesType> taxes;
    @XmlElement(required = true)
    protected List<ItemizationType> itemization;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the businessId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * Sets the value of the businessId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBusinessId(String value) {
        this.businessId = value;
    }

    /**
     * Gets the value of the locationId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLocationId(String value) {
        this.locationId = value;
    }

    /**
     * Gets the value of the transactionId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the receiptId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiptId() {
        return receiptId;
    }

    /**
     * Sets the value of the receiptId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiptId(String value) {
        this.receiptId = value;
    }

    /**
     * Gets the value of the serialNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the diningOption property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDiningOption() {
        return diningOption;
    }

    /**
     * Sets the value of the diningOption property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDiningOption(String value) {
        this.diningOption = value;
    }

    /**
     * Gets the value of the creationTime property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the discountMoney property.
     *
     * @return possible object is
     * {@link DiscountMoneyType }
     */
    public DiscountMoneyType getDiscountMoney() {
        return discountMoney;
    }

    /**
     * Sets the value of the discountMoney property.
     *
     * @param value allowed object is
     *              {@link DiscountMoneyType }
     */
    public void setDiscountMoney(DiscountMoneyType value) {
        this.discountMoney = value;
    }

    /**
     * Gets the value of the additiveTaxMoney property.
     *
     * @return possible object is
     * {@link AdditiveTaxMoneyType }
     */
    public AdditiveTaxMoneyType getAdditiveTaxMoney() {
        return additiveTaxMoney;
    }

    /**
     * Sets the value of the additiveTaxMoney property.
     *
     * @param value allowed object is
     *              {@link AdditiveTaxMoneyType }
     */
    public void setAdditiveTaxMoney(AdditiveTaxMoneyType value) {
        this.additiveTaxMoney = value;
    }

    /**
     * Gets the value of the inclusiveTaxMoney property.
     *
     * @return possible object is
     * {@link InclusiveTaxMoneyType }
     */
    public InclusiveTaxMoneyType getInclusiveTaxMoney() {
        return inclusiveTaxMoney;
    }

    /**
     * Sets the value of the inclusiveTaxMoney property.
     *
     * @param value allowed object is
     *              {@link InclusiveTaxMoneyType }
     */
    public void setInclusiveTaxMoney(InclusiveTaxMoneyType value) {
        this.inclusiveTaxMoney = value;
    }

    /**
     * Gets the value of the refundedMoney property.
     *
     * @return possible object is
     * {@link RefundedMoneyType }
     */
    public RefundedMoneyType getRefundedMoney() {
        return refundedMoney;
    }

    /**
     * Sets the value of the refundedMoney property.
     *
     * @param value allowed object is
     *              {@link RefundedMoneyType }
     */
    public void setRefundedMoney(RefundedMoneyType value) {
        this.refundedMoney = value;
    }

    /**
     * Gets the value of the taxMoney property.
     *
     * @return possible object is
     * {@link TaxMoneyType }
     */
    public TaxMoneyType getTaxMoney() {
        return taxMoney;
    }

    /**
     * Sets the value of the taxMoney property.
     *
     * @param value allowed object is
     *              {@link TaxMoneyType }
     */
    public void setTaxMoney(TaxMoneyType value) {
        this.taxMoney = value;
    }

    /**
     * Gets the value of the tipMoney property.
     *
     * @return possible object is
     * {@link TipMoneyType }
     */
    public TipMoneyType getTipMoney() {
        return tipMoney;
    }

    /**
     * Sets the value of the tipMoney property.
     *
     * @param value allowed object is
     *              {@link TipMoneyType }
     */
    public void setTipMoney(TipMoneyType value) {
        this.tipMoney = value;
    }

    /**
     * Gets the value of the totalCollectedMoney property.
     *
     * @return possible object is
     * {@link TotalCollectedMoneyType }
     */
    public TotalCollectedMoneyType getTotalCollectedMoney() {
        return totalCollectedMoney;
    }

    /**
     * Sets the value of the totalCollectedMoney property.
     *
     * @param value allowed object is
     *              {@link TotalCollectedMoneyType }
     */
    public void setTotalCollectedMoney(TotalCollectedMoneyType value) {
        this.totalCollectedMoney = value;
    }

    /**
     * Gets the value of the creator property.
     *
     * @return possible object is
     * {@link CreatorType }
     */
    public CreatorType getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     *
     * @param value allowed object is
     *              {@link CreatorType }
     */
    public void setCreator(CreatorType value) {
        this.creator = value;
    }

    /**
     * Gets the value of the tender property.
     *
     * @return possible object is
     * {@link TenderType }
     */
    public TenderType getTender() {
        return tender;
    }

    /**
     * Sets the value of the tender property.
     *
     * @param value allowed object is
     *              {@link TenderType }
     */
    public void setTender(TenderType value) {
        this.tender = value;
    }

    /**
     * Gets the value of the taxes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxesType }
     */
    public List<TaxesType> getTaxes() {
        if (taxes == null) {
            taxes = new ArrayList<TaxesType>();
        }
        return this.taxes;
    }

    /**
     * Gets the value of the itemization property.
     *
     * @return possible object is
     * {@link ItemizationType }
     */
    public List<ItemizationType> getItemization() {
        return itemization;
    }

    /**
     * Sets the value of the itemization property.
     *
     * @param value allowed object is
     *              {@link ItemizationType }
     */
    public void setItemization(List<ItemizationType> value) {
        this.itemization = value;
    }

}
