//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.11 at 09:49:38 PM EET 
//


package com.pos.transprocessor.input.json;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for taxesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="taxesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="inclusion_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="is_custom_amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applied_money" type="{}applied_moneyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taxesType", propOrder = {
        "id",
        "name",
        "rate",
        "inclusionType",
        "isCustomAmount",
        "appliedMoney"
})
public class TaxesType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String name;
    protected float rate;
    @XmlElement(name = "inclusion_type", required = true)
    protected String inclusionType;
    @XmlElement(name = "is_custom_amount", required = true)
    protected String isCustomAmount;
    @XmlElement(name = "applied_money", required = true)
    protected AppliedMoneyType appliedMoney;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the rate property.
     */
    public float getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     */
    public void setRate(float value) {
        this.rate = value;
    }

    /**
     * Gets the value of the inclusionType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInclusionType() {
        return inclusionType;
    }

    /**
     * Sets the value of the inclusionType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInclusionType(String value) {
        this.inclusionType = value;
    }

    /**
     * Gets the value of the isCustomAmount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsCustomAmount() {
        return isCustomAmount;
    }

    /**
     * Sets the value of the isCustomAmount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsCustomAmount(String value) {
        this.isCustomAmount = value;
    }

    /**
     * Gets the value of the appliedMoney property.
     *
     * @return possible object is
     * {@link AppliedMoneyType }
     */
    public AppliedMoneyType getAppliedMoney() {
        return appliedMoney;
    }

    /**
     * Sets the value of the appliedMoney property.
     *
     * @param value allowed object is
     *              {@link AppliedMoneyType }
     */
    public void setAppliedMoney(AppliedMoneyType value) {
        this.appliedMoney = value;
    }

}
