//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.10 at 11:27:12 PM EET 
//


package com.pos.transprocessor.input.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for elementType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="elementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applied_money" type="{}applied_moneyType" minOccurs="0"/>
 *         &lt;element name="category" type="{}categoryType" minOccurs="0"/>
 *         &lt;element name="discount_money" type="{}discount_moneyType" minOccurs="0"/>
 *         &lt;element name="discounts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gross_sales_money" type="{}gross_sales_moneyType" minOccurs="0"/>
 *         &lt;element name="id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="7424ae3d-36bc-4c0c-b790-310614905aed"/>
 *               &lt;enumeration value="cfc92a12-f847-4942-b6ec-1454d194c9ba"/>
 *               &lt;enumeration value="788cb9cb-106f-4d32-ac48-df9e8433ff50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="inclusion_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="is_custom_amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifiers" type="{}modifiersType" minOccurs="0"/>
 *         &lt;element name="name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="6 Pieces"/>
 *               &lt;enumeration value="Sales Tax"/>
 *               &lt;enumeration value="Boneless Chicken Wings"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="net_sales_money" type="{}net_sales_moneyType" minOccurs="0"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *         &lt;element name="rate" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="single_quantity_money" type="{}single_quantity_moneyType" minOccurs="0"/>
 *         &lt;element name="taxes" type="{}taxesType" minOccurs="0"/>
 *         &lt;element name="total_money" type="{}total_moneyType" minOccurs="0"/>
 *         &lt;element name="variation" type="{}variationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementType", propOrder = {
        "appliedMoney",
        "category",
        "discountMoney",
        "discounts",
        "grossSalesMoney",
        "id",
        "inclusionType",
        "isCustomAmount",
        "modifiers",
        "name",
        "netSalesMoney",
        "quantity",
        "rate",
        "singleQuantityMoney",
        "taxes",
        "totalMoney",
        "variation"
})
public class ElementType {

    @XmlElement(name = "applied_money")
    protected AppliedMoneyType appliedMoney;
    protected CategoryType category;
    @XmlElement(name = "discount_money")
    protected DiscountMoneyType discountMoney;
    protected String discounts;
    @XmlElement(name = "gross_sales_money")
    protected GrossSalesMoneyType grossSalesMoney;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "inclusion_type")
    protected String inclusionType;
    @XmlElement(name = "is_custom_amount")
    protected String isCustomAmount;
    protected ModifiersType modifiers;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "net_sales_money")
    protected NetSalesMoneyType netSalesMoney;
    protected Byte quantity;
    protected Float rate;
    @XmlElement(name = "single_quantity_money")
    protected SingleQuantityMoneyType singleQuantityMoney;
    protected List<TaxesType> taxes;
    @XmlElement(name = "total_money")
    protected TotalMoneyType totalMoney;
    protected VariationType variation;

    /**
     * Gets the value of the appliedMoney property.
     *
     * @return possible object is
     * {@link AppliedMoneyType }
     */
    public AppliedMoneyType getAppliedMoney() {
        return appliedMoney;
    }

    /**
     * Sets the value of the appliedMoney property.
     *
     * @param value allowed object is
     *              {@link AppliedMoneyType }
     */
    public void setAppliedMoney(AppliedMoneyType value) {
        this.appliedMoney = value;
    }

    /**
     * Gets the value of the category property.
     *
     * @return possible object is
     * {@link CategoryType }
     */
    public CategoryType getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is
     *              {@link CategoryType }
     */
    public void setCategory(CategoryType value) {
        this.category = value;
    }

    /**
     * Gets the value of the discountMoney property.
     *
     * @return possible object is
     * {@link DiscountMoneyType }
     */
    public DiscountMoneyType getDiscountMoney() {
        return discountMoney;
    }

    /**
     * Sets the value of the discountMoney property.
     *
     * @param value allowed object is
     *              {@link DiscountMoneyType }
     */
    public void setDiscountMoney(DiscountMoneyType value) {
        this.discountMoney = value;
    }

    /**
     * Gets the value of the discounts property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDiscounts() {
        return discounts;
    }

    /**
     * Sets the value of the discounts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDiscounts(String value) {
        this.discounts = value;
    }

    /**
     * Gets the value of the grossSalesMoney property.
     *
     * @return possible object is
     * {@link GrossSalesMoneyType }
     */
    public GrossSalesMoneyType getGrossSalesMoney() {
        return grossSalesMoney;
    }

    /**
     * Sets the value of the grossSalesMoney property.
     *
     * @param value allowed object is
     *              {@link GrossSalesMoneyType }
     */
    public void setGrossSalesMoney(GrossSalesMoneyType value) {
        this.grossSalesMoney = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the inclusionType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInclusionType() {
        return inclusionType;
    }

    /**
     * Sets the value of the inclusionType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInclusionType(String value) {
        this.inclusionType = value;
    }

    /**
     * Gets the value of the isCustomAmount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsCustomAmount() {
        return isCustomAmount;
    }

    /**
     * Sets the value of the isCustomAmount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsCustomAmount(String value) {
        this.isCustomAmount = value;
    }

    /**
     * Gets the value of the modifiers property.
     *
     * @return possible object is
     * {@link ModifiersType }
     */
    public ModifiersType getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     *
     * @param value allowed object is
     *              {@link ModifiersType }
     */
    public void setModifiers(ModifiersType value) {
        this.modifiers = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the netSalesMoney property.
     *
     * @return possible object is
     * {@link NetSalesMoneyType }
     */
    public NetSalesMoneyType getNetSalesMoney() {
        return netSalesMoney;
    }

    /**
     * Sets the value of the netSalesMoney property.
     *
     * @param value allowed object is
     *              {@link NetSalesMoneyType }
     */
    public void setNetSalesMoney(NetSalesMoneyType value) {
        this.netSalesMoney = value;
    }

    /**
     * Gets the value of the quantity property.
     *
     * @return possible object is
     * {@link Byte }
     */
    public Byte getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     *
     * @param value allowed object is
     *              {@link Byte }
     */
    public void setQuantity(Byte value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the rate property.
     *
     * @return possible object is
     * {@link Float }
     */
    public Float getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     *
     * @param value allowed object is
     *              {@link Float }
     */
    public void setRate(Float value) {
        this.rate = value;
    }

    /**
     * Gets the value of the singleQuantityMoney property.
     *
     * @return possible object is
     * {@link SingleQuantityMoneyType }
     */
    public SingleQuantityMoneyType getSingleQuantityMoney() {
        return singleQuantityMoney;
    }

    /**
     * Sets the value of the singleQuantityMoney property.
     *
     * @param value allowed object is
     *              {@link SingleQuantityMoneyType }
     */
    public void setSingleQuantityMoney(SingleQuantityMoneyType value) {
        this.singleQuantityMoney = value;
    }

    /**
     * Gets the value of the taxes property.
     *
     * @return possible object is
     * {@link TaxesType }
     */
    public List<TaxesType> getTaxes() {
        return taxes;
    }

    /**
     * Sets the value of the taxes property.
     *
     * @param value allowed object is
     *              {@link TaxesType }
     */
    public void setTaxes(List<TaxesType> value) {
        this.taxes = value;
    }

    /**
     * Gets the value of the totalMoney property.
     *
     * @return possible object is
     * {@link TotalMoneyType }
     */
    public TotalMoneyType getTotalMoney() {
        return totalMoney;
    }

    /**
     * Sets the value of the totalMoney property.
     *
     * @param value allowed object is
     *              {@link TotalMoneyType }
     */
    public void setTotalMoney(TotalMoneyType value) {
        this.totalMoney = value;
    }

    /**
     * Gets the value of the variation property.
     *
     * @return possible object is
     * {@link VariationType }
     */
    public VariationType getVariation() {
        return variation;
    }

    /**
     * Sets the value of the variation property.
     *
     * @param value allowed object is
     *              {@link VariationType }
     */
    public void setVariation(VariationType value) {
        this.variation = value;
    }

}
